openapi: 3.0.3

servers:
  - url: "https://r95e08rtmj.execute-api.us-east-1.amazonaws.com/"

info:
  title: HKP Solutions Beta App API
  version: 0.0.1
  description: HKP Solutions Beta App API delivers functionality for all aspects of HKP Solutions Beta Application.
  contact:
    name: Alvan Caleb Arulandu
    email: caleb.arulandu@hkpsolutions.com

paths:
  "/":
    $ref: "./paths/_.yaml"

  "/calculator/add":
    $ref: "./paths/_calculator_add.yaml"

  "/users/sign-up":
    $ref: "./paths/users/_users_sign-up.yaml"

  "/users/confirm-sign-up":
    $ref: "./paths/users/_users_confirm-sign-up.yaml"

  "/users/login":
    $ref: "./paths/users/_users_login.yaml"

  "/hotels":
    $ref: "./paths/hotels/_hotels.yaml"

  "/hotels/{HIN}":
    $ref: "./paths/hotels/_hotels_hin.yaml"

  "/hotels/{HIN}/floors":   
    $ref: "./paths/hotels/_hotels_hin_floors.yaml"

  "/hotels/{HIN}/floors/{floor_id}":
    $ref: "./paths/hotels/_hotels_hin_floors_floorid.yaml"

components:
  securitySchemes:
    bearerAuthorizer:
      type: http
      scheme: bearer
      description: "Uses cognito to validate a JWT authorization token."
